### ISSUE TITLE
Error after upgrading to latest: Module not found: Error: Can't resolve 'process/browser'

### ISSUE THREAD

**Issue by hoIIer** [elwayman02/ember-sinon-qunit#835]
Just upgraded to latest and getting the following error:
```
ERROR in ./node_modules/sinon/pkg/sinon-esm.js 405:74-81
Module not found: Error: Can't resolve 'process/browser' in '/Users/eric/Projects/sqwok/ember-sqwok/node_modules/sinon/pkg'
```
Any suggestions or ideas?

**Comment by elwayman02** [comment]
What exact versions were you upgrading from and to? What version of sinon are you using?

The esm module is handled by ember-auto-import here: https://github.com/elwayman02/ember-sinon-qunit/blob/master/index.js#L9

There isn't anything more complex going on, but it seems like it's having some issue internal to sinon?

**Comment by elwayman02** [comment]
@hoIIer we've just released v7.4.0 which no longer uses ember-auto-import for bundling. Can you test again to see if it works for you on the latest version?

**Comment by RobbieTheWagner** [comment]
@elwayman02 I am seeing this on 7.4.0 as well. We have stuff like this in our app:

```js
      webpack: {
        plugins: [
          new webpack.ProvidePlugin({
            process: 'process/browser',
          }),
        ],
```

But it seems that this addon is still not able to find this dependency. To note, we are not on embroider yet.
